---
version: '3'

services:
  crafty:
    container_name: crafty-alpine_container
    image: crafty-alpine:latest
    restart: unless-stopped
    environment:
      - TZ=Etc/UTC
    ports:
      - "8000:8000"  # HTTP
      - "8443:8443"  # HTTPS
      - "8123:8123"  # DYNMAP
      - "19132:19132/udp"  # BEDROCK
      - "25500-25600:25500-25600"  # MC SERV PORT RANGE
    volumes:
      - backups:/crafty/backups
      - logs:/crafty/logs
      - servers:/crafty/servers
      - config:/crafty/app/config
      - import:/crafty/import
volumes:
  backups:
  logs:
  servers:
  config:
  import: